---
- name: "Unset temporary survey field variable"
  set_fact:
    add_survey_field: []

- name: "Field Type | float"
  block:
    - name: "Add survey field | float"
      set_fact:
        add_survey_field: [{question_description: "{{ survey_field.description | default('') }}", min: "{{ survey_field.min | default('0') }}", default: "{{ survey_field.default | default('') }}", max: "{{ survey_field.max | default('100') }}", required: "{{ survey_field.required }}", choices: "", new_question: True, variable: "{{ survey_field.variable }}", question_name: "{{ survey_field.prompt }}", type: "{{ survey_field.type }}"}]
  when: 'survey_field.type == "float"'
#
# - name: "Field Type | integer"
#   block:
#     set_fact:
#   when: 'survey_field.type == "integer"'
#
# - name: "Field Type | multiple-choice multiple-select"
#   block:
#
#   when: 'survey_field.type == "multiple-choice-multi"'
#
# - name: "Field Type | multiple-choice single-select"
#   block:
#
#   when: 'survey_field.type == "multiple-choice-single"'
#
# - name: "Field Type | text-area"
#   block:
#
#   when: 'survey_field.type == "text-area"'
#
# - name: "Field Type | text"
#   block:
#
#   when: 'survey_field.type == "text"'

- name: "Add survey field"
  set_fact:
    tower_survey: "{{ tower_survey | union(add_survey_field) }}"
